### PR TITLE
Fix leaderboard crawler by removing Goerli testnets

### PR DESCRIPTION
**Pull request by renbou**
Hello! Since Goerli was deprecated and removed from Ethernaut in https://github.com/OpenZeppelin/ethernaut/pull/699, it should also be removed from the leaderboard crawler. Currently, since Goerli has been completely disabled, the crawler isn't able to work at all (alchemy Goerli addresses don't resolve to an IP anymore). As an incomplete fix for this I've simply removed the Goerli networks from the `networkDetails.json` file. Tested this with Mumbai, seems to be working locally.

I've also pulled all the necessary updates from the `update` branch (took the files which appeared in `git diff --name-only main`), so this should be good to go.

Please merge this until someone is able to write a proper patch with the complete removal of the Goerli testnets and addition of the Optimism & Arbitrum Sepolia testnets. At least this way the leaderboard will be getting synced for Mumbai & Sepolia...

### CODE REVIEW

**Comment by jdetychey** [comment]
awesome, thank you for that!

**Comment by renbou** [comment]
@xaler5 @JithinKS97 Hi! You guys seem to be the main maintainers, can this get merged so that the leaderboard starts working again?

**Comment by JithinKS97** [comment]
After removing goerli from the config, have you ran the crawler again to correct the data?

**Comment by renbou** [comment]
I won't be able to run it properly since it requires a key for your HubSpot API, no? If it's public I can try setting it up and running it, I'm not too familiar with HubSpot. Other than that I've tried launching it to check that it properly works, but for that I've commented out the calls to the aliasing API.

**Comment by JithinKS97** [comment]
@jdetychey @renbou I no longer maintain the repo. I had it when my current organization had a collaboration with Openzeppelin. I think we might need someone from Openzeppelin to run it since they own the keys. @xaler5 Can you help us?

**Comment by xaler5** [comment]
@GianfrancoBazzani is taking care of this PR currently syncing old blocks of all chains with the leaderboard. It will take some time please bear with us :)

**Review by GianfrancoBazzani — APPROVED** [review]
LGTM! Sorry for the delay guys, we had to synch all pending blocks

**Pull request merged**
